class FilmStripGrailsPlugin {
    def version = "0.1.7-SNAPSHOT"
    def grailsVersion = "2.1 > *"
    def pluginExcludes = [
        "README.adoc",
        "src/doc/**",
        "scripts/Arc42GenerateHtmlFromAsciiDoc.groovy",
        "scripts/_githubIssues2AsciiDoc.groovy"
    ]
    def title = "Film Strip Plugin"
    def author = "Ralf D. Müller"
    def authorEmail = "ralf.d.mueller@gmail.com"
    def description = 'Creates a nice HTML-view showing all screenshots generated by Geb.'
    def documentation = "https://github.com/rdmueller/grails-filmStrip/"
    def license = "APACHE"
    def issueManagement = [ system: "github", url: "https://github.com/rdmueller/grails-filmStrip/issues" ]
    def scm = [ url: "https://github.com/rdmueller/grails-filmStrip/" ]
}
