class FilmStripGrailsPlugin {
    def version = "0.1.2"
    def grailsVersion = "2.2 > *"
    def pluginExcludes = [
        "README.adoc"
    ]
    def title = "Film Strip Plugin"
    def author = "Ralf D. Müller"
    def authorEmail = "ralf.d.mueller@gmail.com"
    def description = 'Creates a nice HTML-view showing all screenshots generated by Geb.'
    def documentation = "https://github.com/rdmueller/grails-filmStrip/"
    def license = "APACHE"
    def issueManagement = [ system: "github", url: "https://github.com/rdmueller/grails-filmStrip/issues" ]
    def scm = [ url: "https://github.com/rdmueller/grails-filmStrip/" ]
}
