[[section-introduction-and-goals]]
== Introduction and Goals

Geb -- together with Spock -- is a great combination if you need to create functional tests for your Grails application.
But the output is basically just the information that the tests succeeded -- at least when there was no failure :-) +
Out of the box, it does not report on *what* has been tested. If you want to get details about the tests, you are
expected to read the sources.

A not so well known feature of Geb is the http://www.gebish.org/manual/current/testing.html#reporting[++report++] feature: +
whenever you use the command ++report "some text"++, geb tries to create a screenshot and save the current DOM as HTML.

This plugin crawls through the generated screenshots and creates an HTML report
which displays preview images as a film strip at the top of the report-page and the
test-result on the main part of the window. When you click on an image, it will be displayed
in full size, if you click on the name of a report image, the corresponding HTML
file will be displayed. Without the proper path to referenced files, this view will
look broken, but it is still useful for debugging. When you click on the small star
in front of the name, the link will take you to the recorded original URL of this test --
so if your project is running, you will be taken to the right page on your web server
and you can manually verify what happened.

The aim of this plugin is not only to help a tester in developing Geb/Spock tests
and see what went wrong, but also to create a report for your customer. With all
those screenshots you can easily get an graphical overview of the application and
see if all pages display correctly.

=== Quickstart

There is not much to do in order to use the plugin. Just configure it in your ++BuildConfig.groovy++

    test ':film-strip:0.1.1'

and add the folowing line to your gebConfig.groovy:

    reportingListener = new grails.plugin.filmstrip.FilmStripReportingListener()

If your geb reportDir is the standard one, the report will be generated after running grails test-app.

You will find the generated report in ++target/test-reports/geb++

=== Requirements Overview

[options="header",cols="1,2,10"]
|===
|ID       |Priority | Description
|[[R1]]R1 |high     | the system has to produce an easy to navigate visual report
				   containing all screenshots reported by geb
|[[R2]]R2 |medium   | the system has to be easy to use. Best would be install and
                   run with some reasonable default configs
|[[R3]]R3 |medium   | the system should be configurable in terms of html output
                   and css style. Some kind of jsp template should be available
|[[R4]]R4 |low      | no magic strings. All parameters like output directory should
				   be configurable
|===

=== Quality Goals

[options="header",cols="1,6"]
|===
|Type          | Description
|performance   | since tests should run fast, performance is important. Report
				 should be generated in less than 2 seconds
|modifiability | every Grails developer should be able to modify the plugin in
				 order to fit his needs
|availability  | plugin should be available through central plugin repository
				 and as download
|security	   | once installed, the plugin must not connect to the internet
|testability   | it would be nice if there where automated tests
|usability     | install and run with reasonable default configs. See <<R2>>
|===

=== Stakeholders

These are the stakeholders I (Ralf D. Müller) had in mind when I started to code
this plugin and I am open for discussions :-)

[options="header",cols="<.<1,<.<3,<.<2"]
|===
| Role/Name | Goal/Boundaries | Expected Participation and Contribution
| Developer    | wants to proof to BA that her
				 software is covered with
				 automated tests 				| Need direct feedback from other developers through
						  		   				  issue tracking or direct mail
| Business
  Analyst (BA) | wants to specify tests in
  				 natural language and wants to
  				 be able to read test reports	| Hope for indirect feedback through developers
| Contractor   | wants to proof to client
                 that his software is
                 thourougly tested and uses
                 screenshot to have a proof
                 for the look and feel at a
                 certain point in time			| Hope for indirect feedback through developers
| Designer     | wants to see that his design
                 is implemented the right way
                 and may want to compare screens| Hope for indirect feedback through developers
|===

==== Personas

The following section will describe some fictional stakeholders. The intention is
to add some more to the stakeholder description above and to allow you to easily
switch into the role of a stakeholder.

Melanie Schmitt:: Melanie works as a freelancer in the role of a *developer*. She is used to write automated tests for her code. She would now like to use the test results as some kind of acceptance report. When she delivers a release, she wants to have a report ready which can be signed of by the customer as soon as he accepts the delivered features. +
She also made the experience that sometimes customers report a bug where it is not clear if it is really a bug or works as designed. Through a history of proper test reports with screenshots, she hopes to be able to easily prove that it's not a bug but a change the customer has to pay for (because it was this way all the time). +
Those two features will help Melanie to be recognized as professional developer and optimize her effort/Value ratio.

Peter Miller:: Peter is a *business analyst* who works together with a team of developers on larger projects. He would like to specify automated tests but has not enough technical background to write test scripts. He also does not like to have a development environment up and running in order to run the tests by himself but he would like to have a good looking report which helps him to check if the tests have been executed in the intended way. +
The goal for Peter is to write tests in natural language and hand them over to the developers. They will then turn them into executable tests and generate tests reports for each new release. The reports are handed back to Peter for an acceptance sign-off.

Henry Ford:: Henry is a *developer* who works together with Peter. Henry needs a way to add readable code to the natural language test description (received from Peter) and combine both in a report. When Henry runs his tests, he can watch his web browser execute the tests and he sees if something looks wrong. But he also would like to have those screens as screenshots included in his report. In case that Peter complains about a specific test in the generated report, the report should include enough detail for Henry to figure out what code has been executed for the test in order to easily see what's going on.

Steve Bauer:: Steve is a *designer* who needs to make sure that his design guidelines are followed by the developers. He doesn't care about the functionality of the application, only the screens. So he needs a report where he can flip through all screens and see if he can find a design flaw.
