[[section-system-scope-and-context]]
== System Scope and Context

The main scope of the project is to extract a model from the data generated by geb
through the execution of +grails run-app functional+. In order to visualize the
model, the plugin will also generate some HTML to browse through the data.

Currently, data generated by spock is out of scope, but it is planned to take
this in scope for the next iteration.

=== External Interfaces

Since the plugin should be easy to handle, it should use some automated way to gather the data.

In order to do this, the following interfaces to Grails and Geb have been identified:

Event System::
The plugin will hook into the reporting events in order to setup the collection of
data (+eventTestPhasesStart+) and to generate the reports (+eventTestProduceReports+)

Geb http://www.gebish.org/manual/0.9.2/api/geb/report/ReportingListener.html[+ReportingListener+]::
The ReportingListener has been identified as the right interface to Geb. It will
notify the plugin every time the +report+ command has been executed and will provide
the needed data. Currently, no automated way has been identified to add the plugin's
own +ReportingListener+ to the +gebConfig+ in an automated way, so the developer has
to add it by herself.
